### PR TITLE
Switch OpenWeatherMap API URLs to HTTPS

### PR DESCRIPTION
**Pull request by SpotComms**
See http://openweathermap.org/news/post/ssl-free-and-startup-accounts

### CODE REVIEW

**Comment by Sparker0i** [comment]
Hey there,

Since the last few builds, travis has been giving me error in building. I'm not able to verify what the error is, so meanwhile can you post the screenshot of the app working on your phone (with this commit), and also attach the debug apk?

**Comment by SpotComms** [comment]
@Sparker0i  I've not actually compiled this as I've made this commit to multiple weather apps, but I can confirm that HTTPS API access does indeed work.

**Comment by Sparker0i** [comment]
The build has failed. I cannot accept this ATM. Do consider sending another PR without Travis part

**Comment by SpotComms** [comment]
That Travis commit does fix one issue, it seems there is another issue however. I've removed it.

**Pull request closed without merging**
