### PR TITLE
Option to change time format from 12 to 24 and back, closes #40

### LINKED ISSUE #40: 12 vs 24 hour time
A setting to display the time (e.g. for sunrise and sunset) in 12 versus 24 hour notation would be nice (a.m./p.m. versus military time).

### PR DESCRIPTION
**Pull request by kartikarora**
Added the feature and tested it out. Following is the change summary:

- Create a preference to change time format setting, defaults to `false`
- Added related strings in `nontranslatable.xml`, `string.xml` (default) and `Constants.java`
- Added getter in `Prefs.java`
- Added related java code in `WeatherFragment.java`

### CODE REVIEW

**Comment by Sparker0i** [comment]
Hi, inside WeatherFragment, you put the declaration of the View objects bound to `@BindView` in a newline. Could you please undo that and keep the declaration and `@BindView` in one line?

Thanks

**Comment by kartikarora** [comment]
Oh, I just let Android Studio refactor the indentation. I'll change it and push the commit.

**Comment by kartikarora** [comment]
@Sparker0i Done.

**Comment by Sparker0i** [comment]
Thanks :+1:

**Pull request merged**
