### PR TITLE
Added_splash_screen

### PR DESCRIPTION
**Pull request by ayush251196**
The splash screen is visible only during the data the loading duration.

### CODE REVIEW

**Comment by Sparker0i** [comment]
Can you put up a GIF showing:
- How the splash screen shows when the app starts
- When you change the city (by clicking the OK button inside the City Change dialog when you press the search FAB) showing whether the city change is successful or not.

**Comment by ayush251196** [comment]
https://drive.google.com/open?id=1KOeTWrc97NDmJ4sDAeQb0xzK9PJyTs0s

**Comment by Sparker0i** [comment]
This completely defeats the purpose of having a splash screen in the app. The splash screen should be the one which loads the data (if the city has been set) and then redirect to the WeatherActivity and display the WeatherFragment.

Moreover, the black screen is also coming up whenever the city is being changed. This is definitely not a splash screen, because a splash screen is supposed to come only when the app starts (that is why it has the name splash screen).

Further, the "Weather App" written in some font for the GlobalActivity was unnecessary. You could have simply displayed the App's icon from the drawable/mipmap.

**Comment by ayush251196** [comment]
What I have learnt from various blogs tjat its not a good practice to load everything in the splash screen.Then particularly in your case as there is no caching mechanism  everytime the user opens he will get stuck at splash screen waiting for data to load.
What I have seen in commercial apps like Amazon prime etc that they dun load entire data  in the splash screen but data is loaded when required and they frequently use loading black screen(loading fragment) like I have used to show the user that data is being loaded.
Btw I will do wat u require.

**Pull request closed without merging**
